services:
  user-service:
    image: neerajbabu/user # image name given to build file
    build: ./services/user_service # build source
    container_name: ecomm_user_service # container name
    depends_on:
      - user-database
    ports:
      - 8000:8000
    environment:
      - JWT_SECRET=value
      - DB_NAME=user
      - DB_USER=postgres
      - DB_HOST=user-database # database service name
      - DB_PASS=postgres

  user-database:
    image: postgres:17
    container_name: ecomm_user_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - user_database_data:/var/lib/postgresql/data
      - user_database_data_backup:/backups

volumes:
  user_database_data:
    driver: local
  user_database_data_backup:
    driver: local