services:
  user-service:
    image: neerajbabu/user-service # image name given to build file
    build:
      context: ./services/user-service # set working folder for build
      dockerfile: Dockerfile # build source
    container_name: user-service # container name
    depends_on:
      - user-database
    ports:
      - 8000:8000
    environment:
      - JWT_SECRET=value
      - DB_NAME=user
      - DB_USER=postgres
      - DB_HOST=user-database # database service name
      - DB_PASS=postgres
      - DB_PORT=5432
    volumes:
      - ./services/user-service:/app
    command: /start.dev.sh

  user-database:
    image: postgres:17
    container_name: user-database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - user_database_data:/var/lib/postgresql/data
      - user_database_data_backup:/backups

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    
volumes:
  user_database_data:
    driver: local
  user_database_data_backup:
    driver: local
  prometheus_data:
    driver: local