#!/bin/sh

set -e # exit on error

>&2 echo "Wating for PostgreSQl..." # print to stderr

# checking for postgres using python
python << END
import sys
import time

import psycopg2

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        psycopg2.connect(
            dbname="${DB_NAME}",
            user="${DB_USER}",
            password="${DB_PASS}",
            host="${DB_HOST}",
            port="${DB_PORT}",
        )
        break
    except psycopg2.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

python manage.py makemigrations
python manage.py migrate --noinput # no interaction
# python manage.py collectstatic --noinput

# exec "$@" # run command passed as argument

exec python manage.py runserver 0.0.0.0:8000 # replace the current shell with command