name: CI

on:
  push:
    branches:
      - main

jobs:

  detect-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed directories
        id: set-matrix
        run: |
          changed=$(git diff --name-only ${{ github.event.pull_request.base.ref }} ${{ github.github.event.pull_request.base.sha }} | cut -d/ -f1 | sort -u)
          services=()
          for dir in $changed; do
            if [ -f "$dir/Dockerfile" ]; then
              services+=("\"$dir"\")
            fi
          done
          matrix="{\"include\": [$(IFS=,; echo "${services[*]}")]}"
          echo "matrix=$matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
  
  build-and-push:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.matrix != '{}'
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          service=${{ matrix.include }}
          tag=${GITHUB_SHA::8}
          docker build -t myrepo/$service:$tag ./$service
          docker push myrepo/$service:$tag
